services:
  postgres:
    image: postgres:15
    container_name: checkout-postgres
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: grafana
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/data  # Opcional aqui, mas útil se quiser importar via COPY do SQL
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: checkout-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - postgres
    networks:
      - monitor-net

  # --- NOVO SERVIÇO ---
  monitor-app:
    build: ./monitor
    container_name: checkout-monitor
    depends_on:
      - postgres
    volumes:
      - ./data:/data # Coloque seus CSVs na pasta ./data do host
    environment:
      - DB_HOST=postgres
      - DB_NAME=checkout
      - DB_USER=grafana
      - DB_PASS=grafana
    ports:
      - "5000:5000"
    networks:
      - monitor-net

volumes:
  grafana-data:
  postgres-data:

networks:
  monitor-net:
    driver: bridge